import { test, expect } from '@playwright/test';

test('contact form', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('link', { name: 'Contact' }).click();
  await expect(page.getByRole('textbox', { name: 'Nome' })).toBeEmpty();
  await expect(page.getByText('Nome')).toBeVisible();
  await expect(page.getByText('E-mail')).toBeVisible();
  await page.getByRole('textbox', { name: 'E-mail' }).fill('llsdkaçskd');
  await expect(page.getByText('Senha')).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Senha' })).toBeEmpty();
  await page.getByRole('textbox', { name: 'Senha' }).fill('anders');
  await expect(page.getByText('Mínimo de 8 caracteres.')).toBeVisible();
  await expect(page.getByText('Deve conter pelo menos um nú')).toBeVisible();
  await expect(page.getByText('Deve conter pelo menos um caractere especial.')).toBeVisible();
  await expect(page.getByText('Número (number)')).toBeVisible();
  await expect(page.getByRole('spinbutton', { name: 'Número (number)' })).toBeEmpty();
  await page.getByRole('spinbutton', { name: 'Número (number)' }).fill('65');
  await expect(page.getByText('Telefone (tel)')).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Telefone (tel)' })).toBeEmpty();
  await page.getByRole('textbox', { name: 'Telefone (tel)' }).fill('98651524');
  await expect(page.getByText('Site (url)')).toBeVisible();
  await page.getByRole('textbox', { name: 'Site (url)' }).click();
  await page.getByRole('textbox', { name: 'Site (url)' }).fill('google.jp');
  await expect(page.getByText('Data (date)')).toBeVisible();
  await page.getByRole('textbox', { name: 'Data (date)' }).fill('2026-04-08');
  await expect(page.getByText('Intervalo (range)')).toBeVisible();
  await page.getByRole('slider', { name: 'Intervalo (range)' }).fill('65');
  await page.getByLabel('switch de campos').selectOption('br');
  await expect(page.getByText('Preferência de contato (radio)')).toBeVisible();
  await expect(page.getByText('Número do WhatsApp')).not.toBeVisible();
  await page.getByText('WhatsApp').click();
  await expect(page.getByText('Número do WhatsApp')).toBeVisible();
  await page.getByRole('textbox', { name: 'Número do WhatsApp' }).click();
  await page.getByRole('textbox', { name: 'Número do WhatsApp' }).fill('4');
  await expect(page.getByText('Apenas letras são permitidas.')).toBeVisible();
  await page.getByLabel('switch de campos').selectOption('us');
  await expect(page.getByText('Interesses (checkbox)')).toBeVisible();
  await page.getByText('Desenvolvimento').click();
  await page.getByText('Design').click();
  await page.getByLabel('switch de campos').selectOption('uk');
  await expect(page.getByText('Mensagem (textarea)')).toBeVisible();
  await page.getByRole('textbox', { name: 'Mensagem (textarea)' }).click();
  await page.getByRole('textbox', { name: 'Mensagem (textarea)' }).fill('asdsadsadsadsadsadsadsdsdasdsadsadsadasdasdasdsadasdasdsadsadsadsadasdsadsadsadasdsadasdasdasdasdasdasdasdasdasdsadsadasdasdasdasd');
  await page.getByLabel('switch de campos').selectOption('br');
  await expect(page.getByText('Preferência de contato (radio)')).toBeVisible();
  await expect(page.getByText('Número do WhatsApp')).not.toBeVisible();
  await page.getByText('WhatsApp').click();
  await expect(page.getByText('Número do WhatsApp')).toBeVisible();
});